tasks:
  - name: npm-init
    init: npm install && npm run build
    command: npm run start
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
